version: "3.7"

services:
  app:
    user: developer
    hostname: ethereum-tracker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /workspace
    working_dir: /workspace
    command: sleep infinity
    environment:
      BUNDLE_PATH: vendor/bundle
    ports:
      - "9292:9292"
